// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,keep_empty_files=false"
// @generated from file health/v1/health.proto (package health.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file health/v1/health.proto.
 */
export const file_health_v1_health: GenFile = /*@__PURE__*/
  fileDesc("ChZoZWFsdGgvdjEvaGVhbHRoLnByb3RvEgloZWFsdGgudjEiDgoMQ2hlY2tSZXF1ZXN0IjIKDUNoZWNrUmVzcG9uc2USDgoGc3RhdHVzGAEgASgJEhEKCWRiX3N0YXR1cxgCIAEoCTJLCg1IZWFsdGhTZXJ2aWNlEjoKBUNoZWNrEhcuaGVhbHRoLnYxLkNoZWNrUmVxdWVzdBoYLmhlYWx0aC52MS5DaGVja1Jlc3BvbnNlQqcBCg1jb20uaGVhbHRoLnYxQgtIZWFsdGhQcm90b1ABWkRnaXRodWIuY29tL0FrYXNoLU1hbmlrYW5kYW4vYmxvZ2dlci1zZXJ2aWNlL3Byb3RvL2hlYWx0aC92MTtoZWFsdGh2MaICA0hYWKoCCUhlYWx0aC5WMcoCCUhlYWx0aFxWMeICFUhlYWx0aFxWMVxHUEJNZXRhZGF0YeoCCkhlYWx0aDo6VjFiBnByb3RvMw");

/**
 * @generated from message health.v1.CheckRequest
 */
export type CheckRequest = Message<"health.v1.CheckRequest"> & {
};

/**
 * Describes the message health.v1.CheckRequest.
 * Use `create(CheckRequestSchema)` to create a new message.
 */
export const CheckRequestSchema: GenMessage<CheckRequest> = /*@__PURE__*/
  messageDesc(file_health_v1_health, 0);

/**
 * @generated from message health.v1.CheckResponse
 */
export type CheckResponse = Message<"health.v1.CheckResponse"> & {
  /**
   * @generated from field: string status = 1;
   */
  status: string;

  /**
   * @generated from field: string db_status = 2;
   */
  dbStatus: string;
};

/**
 * Describes the message health.v1.CheckResponse.
 * Use `create(CheckResponseSchema)` to create a new message.
 */
export const CheckResponseSchema: GenMessage<CheckResponse> = /*@__PURE__*/
  messageDesc(file_health_v1_health, 1);

/**
 * @generated from service health.v1.HealthService
 */
export const HealthService: GenService<{
  /**
   * @generated from rpc health.v1.HealthService.Check
   */
  check: {
    methodKind: "unary";
    input: typeof CheckRequestSchema;
    output: typeof CheckResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_health_v1_health, 0);

