// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,keep_empty_files=false,import_extension=js"
// @generated from file auth/v1/auth.proto (package auth.v1, syntax proto3)
/* eslint-disable */

import type { GenExtension, GenFile } from "@bufbuild/protobuf/codegenv1";
import { extDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";
import type { MethodOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file auth/v1/auth.proto.
 */
export const file_auth_v1_auth: GenFile = /*@__PURE__*/
  fileDesc("ChJhdXRoL3YxL2F1dGgucHJvdG8SB2F1dGgudjE6RQoNcmVxdWlyZXNfYXV0aBIeLmdvb2dsZS5wcm90b2J1Zi5NZXRob2RPcHRpb25zGNCGAyABKAhSDHJlcXVpcmVzQXV0aEKSAQoLY29tLmF1dGgudjFCCUF1dGhQcm90b1ABWjtnaXRodWIuY29tL0FrYXNoLU1hbmlrYW5kYW4vYmxvZ2dlci1iZS9wcm90by9hdXRoL3YxO2F1dGh2MaICA0FYWKoCB0F1dGguVjHKAgdBdXRoXFYx4gITQXV0aFxWMVxHUEJNZXRhZGF0YeoCCEF1dGg6OlYxYgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * @generated from extension: bool requires_auth = 50000;
 */
export const requires_auth: GenExtension<MethodOptions, boolean> = /*@__PURE__*/
  extDesc(file_auth_v1_auth, 0);

