// @generated by protoc-gen-es v2.2.3 with parameter "target=ts,keep_empty_files=false"
// @generated from file user/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user/v1/user.proto.
 */
export const file_user_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChJ1c2VyL3YxL3VzZXIucHJvdG8SB3VzZXIudjEidgoRQ3JlYXRlVXNlclJlcXVlc3QSLAoIdXNlcm5hbWUYASABKAlCGrpIF3IVEAMYFDIPXlthLXpBLVowLTlfXSskEhYKBWVtYWlsGAIgASgJQge6SARyAmABEhsKCHBhc3N3b3JkGAMgASgJQgm6SAZyBBAGGDIieAoSQ3JlYXRlVXNlclJlc3BvbnNlEgoKAmlkGAEgASgJEhAKCHVzZXJuYW1lGAIgASgJEg0KBWVtYWlsGAMgASgJEhIKCmNyZWF0ZWRfYXQYBCABKAkSEgoKdXBkYXRlZF9hdBgFIAEoCRINCgV0b2tlbhgGIAEoCSJDCgxMb2dpblJlcXVlc3QSFgoFZW1haWwYASABKAlCB7pIBHICYAESGwoIcGFzc3dvcmQYAiABKAlCCbpIBnIEEAYYMiJzCg1Mb2dpblJlc3BvbnNlEg0KBXRva2VuGAEgASgJEg0KBWVtYWlsGAIgASgJEhAKCHVzZXJuYW1lGAMgASgJEgoKAmlkGAQgASgJEhIKCmNyZWF0ZWRfYXQYBSABKAkSEgoKdXBkYXRlZF9hdBgGIAEoCSIzCgRVc2VyEgoKAmlkGAEgASgJEhAKCHVzZXJuYW1lGAIgASgJEg0KBWVtYWlsGAMgASgJMowBCgtVc2VyU2VydmljZRJFCgpDcmVhdGVVc2VyEhoudXNlci52MS5DcmVhdGVVc2VyUmVxdWVzdBobLnVzZXIudjEuQ3JlYXRlVXNlclJlc3BvbnNlEjYKBUxvZ2luEhUudXNlci52MS5Mb2dpblJlcXVlc3QaFi51c2VyLnYxLkxvZ2luUmVzcG9uc2VClwEKC2NvbS51c2VyLnYxQglVc2VyUHJvdG9QAVpAZ2l0aHViLmNvbS9Ba2FzaC1NYW5pa2FuZGFuL2Jsb2dnZXItc2VydmljZS9wcm90by91c2VyL3YxO3VzZXJ2MaICA1VYWKoCB1VzZXIuVjHKAgdVc2VyXFYx4gITVXNlclxWMVxHUEJNZXRhZGF0YeoCCFVzZXI6OlYxYgZwcm90bzM");

/**
 * @generated from message user.v1.CreateUserRequest
 */
export type CreateUserRequest = Message<"user.v1.CreateUserRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string password = 3;
   */
  password: string;
};

/**
 * Describes the message user.v1.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema: GenMessage<CreateUserRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 0);

/**
 * @generated from message user.v1.CreateUserResponse
 */
export type CreateUserResponse = Message<"user.v1.CreateUserResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string created_at = 4;
   */
  createdAt: string;

  /**
   * @generated from field: string updated_at = 5;
   */
  updatedAt: string;

  /**
   * @generated from field: string token = 6;
   */
  token: string;
};

/**
 * Describes the message user.v1.CreateUserResponse.
 * Use `create(CreateUserResponseSchema)` to create a new message.
 */
export const CreateUserResponseSchema: GenMessage<CreateUserResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 1);

/**
 * @generated from message user.v1.LoginRequest
 */
export type LoginRequest = Message<"user.v1.LoginRequest"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message user.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 2);

/**
 * @generated from message user.v1.LoginResponse
 */
export type LoginResponse = Message<"user.v1.LoginResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: string id = 4;
   */
  id: string;

  /**
   * @generated from field: string created_at = 5;
   */
  createdAt: string;

  /**
   * @generated from field: string updated_at = 6;
   */
  updatedAt: string;
};

/**
 * Describes the message user.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 3);

/**
 * @generated from message user.v1.User
 */
export type User = Message<"user.v1.User"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;
};

/**
 * Describes the message user.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_user_v1_user, 4);

/**
 * @generated from service user.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.v1.UserService.CreateUser
   */
  createUser: {
    methodKind: "unary";
    input: typeof CreateUserRequestSchema;
    output: typeof CreateUserResponseSchema;
  },
  /**
   * @generated from rpc user.v1.UserService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user_v1_user, 0);

